version: '3.8'

networks:
  go-eda:
    driver: bridge

services:
  # Order Service
  order-service:
    build:
      context: ./services/order-service
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_REGION=eu-central-1
      - QUEUE_URL=http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/orders
      - SNS_TOPIC_ARN=arn:aws:sns:eu-central-1:000000000000:order-topic
      - MYSQL_HOST=mysql-order
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpass
      - MYSQL_DATABASE=orderdb
    ports:
      - "8081:8080"
    depends_on:
      - mysql-order
    networks:
      - go-eda

  # Payment Service
  payment-service:
    build:
      context: ./services/payment-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql-payment
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_REGION=eu-central-1
      - ORDERS_QUEUE_URL=http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/orders
      - PAYMENTS_QUEUE_URL=http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/payments
      - SNS_PAYMENT_TOPIC_ARN=arn:aws:sns:eu-central-1:000000000000:payment-topic
      - SNS_ORDER_TOPIC_ARN=arn:aws:sns:eu-central-1:000000000000:order-topic
      - MYSQL_HOST=mysql-payment
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpass
      - MYSQL_DATABASE=paymentdb
    networks:
      - go-eda

  # Food Preparation Service
  food-preparation-service:
    build:
      context: ./services/food-preparation-service
    ports:
      - "8083:8080"
    depends_on:
      - mysql-food
    networks:
      - go-eda

  # Delivery Service
  delivery-service:
    build:
      context: ./services/delivery-service
    ports:
      - "8084:8080"
    depends_on:
      - mysql-delivery
    networks:
      - go-eda

  # MySQL Databases for each service
  mysql-order:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: orderdb
    ports:
      - "3306:3306"
    networks:
      - go-eda

  mysql-payment:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: paymentdb
    ports:
      - "3307:3306"
    networks:
      - go-eda

  mysql-food:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fooddb
    ports:
      - "3308:3306"
    networks:
      - go-eda

  mysql-delivery:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: deliverydb
    ports:
      - "3309:3306"
    networks:
      - go-eda

  # LocalStack for SQS and SNS
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs,sns
    ports:
      - "4566:4566"
    networks:
      - go-eda

  # AWS CLI container to set up queues and topics
  aws-cli:
    image: amazon/aws-cli
    command: /bin/sh -c "/init-sqs-sns.sh"
    volumes:
      - ./init-sqs-sns.sh:/init-sqs-sns.sh
    depends_on:
      - localstack
    networks:
      - go-eda
